name: 'philip_coomber'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  'dbt_date:time_zone': 'Europe/Amsterdam'

models:
  philip_coomber: # the name of a project
    staging_pii:
      +pre-hook: ["{{ pii_tag_check() }}"]
